"""Import every persistence module, so its tables are registered.

Autogenerate compares the metadata it can see against the database, and a model that
was never imported is invisible. Its absence then reads as "this table should be
dropped", which is how an autogenerated migration deletes a table nobody meant to
touch.

Walking the package means completeness does not depend on somebody remembering to
add a line here when they add an entity. A test asserts that the number of tables
this discovers matches the number of table declarations in the source, so a module
that somehow escapes the walk fails the build rather than producing a migration that
drops a table.
"""

from __future__ import annotations

import importlib
import pkgutil
from typing import Final

CRUD_PACKAGE_NAME: Final[str] = "ahia.crud"


def import_all_record_modules() -> list[str]:
    """Import every module in the CRUD package and return the names imported."""
    package = importlib.import_module(CRUD_PACKAGE_NAME)
    imported: list[str] = []
    for module_info in sorted(pkgutil.iter_modules(package.__path__), key=lambda info: info.name):
        if module_info.name.startswith("_") or module_info.name == "table_registry":
            continue
        module_name = f"{CRUD_PACKAGE_NAME}.{module_info.name}"
        importlib.import_module(module_name)
        imported.append(module_name)
    return imported
