"""Alembic environment.

Two decisions worth stating.

The URL comes from application settings, not from alembic.ini
    A credential in a committed configuration file is a credential in version
    control. The settings object is also the one place that knows about the
    migration URL, which by convention is the direct one rather than the pooled
    endpoint: a migration that alters many objects in a single transaction must not
    be routed to different backends part-way through.

Every table is imported before autogenerate runs
    Autogenerate compares the metadata it can see against the database. A model that
    was never imported is invisible, and its absence reads as "this table should be
    dropped" - which is how an autogenerated migration deletes a table nobody meant
    to touch. `import_all_record_modules` imports every CRUD module by walking the
    package, so completeness does not depend on somebody remembering to add a line.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from ahia.core.config import load_settings
from ahia.core.database import Base
from ahia.crud.table_registry import import_all_record_modules

# Importing every record module registers its table on Base.metadata. Without this,
# autogenerate would propose dropping tables it cannot see.
import_all_record_modules()

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _settings_url() -> str:
    """Return the URL migrations should use.

    Raises through the application's own configuration error when the environment is
    incomplete, so a missing variable fails here exactly as it fails at startup.
    """
    return load_settings().migration_database_url


def run_migrations_offline() -> None:
    """Emit SQL without connecting, for review or for a manual run.

    Offline mode is how a migration is inspected before it is applied to a database
    that matters.
    """
    context.configure(
        url=_settings_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Type and server-default drift is reported rather than silently ignored: a
        # column whose type changed in code but not in the database is a defect that
        # otherwise surfaces as a runtime error months later.
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    configuration = dict(config.get_section(config.config_ini_section) or {})
    configuration["sqlalchemy.url"] = _settings_url()

    connectable = async_engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
