"""notifications: what the product decided to tell somebody

The record the in-app channel reads. Whatever eventually delivers a notification, the fact that it
was raised, for whom and whether it was read lives here.

The dedupe key is unique per recipient, per business, where it is present
    `UNIQUE(tenant_id, recipient_user_id, dedupe_key) WHERE dedupe_key IS NOT NULL`. A scheduled
    evaluator runs on a timer and a product that was low on Tuesday is still low on Wednesday:
    without this the same person receives the same alert every hour until they stop reading any of
    them. The partial clause is what lets a notification raised by hand - with no key to dedupe on -
    coexist with the ones a job raises.

`recipient_user_id` is a real reference
    A notification addressed to somebody who does not exist is a row nobody can ever read, and the
    reader filters on this column. The index on `(tenant_id, recipient_user_id, read_at)` is what
    makes the unread count a query rather than a counter column that a rollback would leave wrong.

`entity_id` is not a foreign key
    A notification can be about a product today and a sale tomorrow, and a column per subject would
    make this table depend on every module that can raise one.

Nothing deletes a notification
    An inbox that empties itself cannot answer "was anybody told", and the answer matters more than
    the tidiness. `read_at` records acknowledgement; there is no delete path in the repository.

Revision ID: e4b5f67bc3fd
Revises: 0d4d04ff5d83
Create Date: 2026-09-15 11:12:00.000000

Generated where autogenerate was sufficient, reviewed before it was applied, and
edited by hand wherever a constraint the database should enforce is not something
autogenerate can infer.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e4b5f67bc3fd"
down_revision: str | None = "0d4d04ff5d83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("notification_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=128), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_notifications_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_recipient_created",
        "notifications",
        ["tenant_id", "recipient_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_recipient_read",
        "notifications",
        ["tenant_id", "recipient_user_id", "read_at"],
        unique=False,
    )
    op.create_index(
        "uq_notifications_tenant_recipient_dedupe",
        "notifications",
        ["tenant_id", "recipient_user_id", "dedupe_key"],
        unique=True,
        postgresql_where=sa.text("dedupe_key IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_notifications_tenant_recipient_dedupe",
        table_name="notifications",
        postgresql_where=sa.text("dedupe_key IS NOT NULL"),
    )
    op.drop_index("ix_notifications_recipient_read", table_name="notifications")
    op.drop_index("ix_notifications_recipient_created", table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
