"""report exports: the metadata for an artifact that lives in object storage

PostgreSQL holds the record, R2 holds the bytes, and this is the record.

The artifact is immutable, and the row has no update path
    A report is what the numbers were when somebody asked. Re-running it produces a second row with
    its own key and its own timestamp, because the two are different answers to the same question -
    and changing the key under a share link already sent would make the link open a different
    document from the one it was sent with.

A failed export keeps its row
    The status, the reason, the key that was attempted and the checksum of what was built are all
    recorded, so an operator can tell a failed upload from a request that was never made. Nothing in
    this revision deletes anything.

`created_by_user_id` is a copy without a foreign key
    It records who asked for the export. A reference would pin a user row for as long as the file
    exists, and the artifact outlives the request that made it.

Reads are by what a business asks
    `(tenant_id, created_at)` for "what has this business exported" and `(tenant_id, report_type,
    created_at)` for "what was exported of this report". Declared with the table rather than
    discovered from a slow screen later.

Revision ID: 0d4d04ff5d83
Revises: 96863e743155
Create Date: 2026-09-15 10:51:00.000000

Generated where autogenerate was sufficient, reviewed before it was applied, and
edited by hand wherever a constraint the database should enforce is not something
autogenerate can infer.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0d4d04ff5d83"
down_revision: str | None = "96863e743155"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_exports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("report_type", sa.String(length=32), nullable=False),
        sa.Column("storage_provider", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("period_since", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_report_exports_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_exports")),
    )
    op.create_index(
        "ix_report_exports_tenant_created",
        "report_exports",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_report_exports_tenant_type_created",
        "report_exports",
        ["tenant_id", "report_type", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_report_exports_tenant_type_created", table_name="report_exports")
    op.drop_index("ix_report_exports_tenant_created", table_name="report_exports")
    op.drop_table("report_exports")
    # ### end Alembic commands ###
