"""share links: revocable public access to one record

The table behind `/share/{token}`: an invoice a business sends a customer, opened by a link whose
token is the authorization.

The token is not in this table
    `token_hash` holds the peppered digest the token service produces, and `UNIQUE` makes the digest
    the lookup key. A public request arrives with a plaintext token, the service digests it and looks
    the row up; the plaintext exists only in the response that created it and in the link the
    business sends. A leaked table therefore yields no working links, which is the difference
    between a share link and an identifier pretending to be one.

Revocation is an update, and it is the only one
    A revoked link keeps its row, its resource and its creation details, because "this invoice was
    shared and then withdrawn" is a fact. `expires_at` is a comparison rather than a flag: a flag
    would need a job to set it, and until that job ran the link would still open.

One resource per link, and the tenant is part of what it opens
    `(tenant_id, resource_type, resource_id)` is indexed, and the public path reads the tenant from
    the link rather than from a caller - there is no caller to read it from. A token from one
    business can therefore never resolve a record in another.

Revision ID: 96863e743155
Revises: fc135a55c7db
Create Date: 2026-09-15 05:46:00.000000

Generated where autogenerate was sufficient, reviewed before it was applied, and
edited by hand wherever a constraint the database should enforce is not something
autogenerate can infer.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "96863e743155"
down_revision: str | None = "fc135a55c7db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "share_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_share_links_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_links")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_share_links_token_hash")),
    )
    op.create_index(
        "ix_share_links_tenant_created", "share_links", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_share_links_tenant_resource",
        "share_links",
        ["tenant_id", "resource_type", "resource_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_share_links_tenant_resource", table_name="share_links")
    op.drop_index("ix_share_links_tenant_created", table_name="share_links")
    op.drop_table("share_links")
    # ### end Alembic commands ###
