"""change feed, device cursors and pushed operations

The three tables offline synchronization needs, and the server-side order that makes a catch-up
possible.

The change feed is the server's memory of what changed
    `sync_changes` holds one row per change with `change_sequence` assigned by an identity column
    that is `generated always`, so an insert that tries to choose its own sequence is refused - a
    device must not be able to place its change in another device's feed. The sequence is global
    rather than per business, which is what makes it a total order; a reader filters by its own
    tenant and asks for everything above the last sequence it applied.

A cursor is one row per device
    `UNIQUE(tenant_id, device_id)` makes two positions in the feed for one phone impossible rather
    than unlikely, and the two writers would be two concurrent requests from that phone. A device
    that has never synchronized has no row: it reads from zero, which is the same value a business
    with no changes reports as its latest sequence.

An operation is recorded once, keyed by the client's identifier inside its business
    `PRIMARY KEY (tenant_id, id)`: the identifier is the device's, and two businesses can generate
    the same one because their phones have never met. The record holds the outcome and the record
    the operation produced, never the payload the client sent - what the client sent is in the
    client's queue, and copying customer names and prices into a second table would create a
    second copy of the business's data with its own retention. There is no update path: an answer
    that could change is not an answer a retrying device can rely on.

`actor_id` and `device_id` are copies without foreign keys, as they are in the audit trail
    These rows record what a request was authenticated as. A reference would pin a device row
    forever and would let a later rename change the answer given to a retry.

Revision ID: 3394dddd7e43
Revises: b3637870a4a9
Create Date: 2026-09-14 16:24:00.000000

Generated where autogenerate was sufficient, reviewed before it was applied, and
edited by hand wherever a constraint the database should enforce is not something
autogenerate can infer.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3394dddd7e43"
down_revision: str | None = "b3637870a4a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("change_sequence", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("change_type", sa.String(length=16), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sync_changes_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_changes")),
        sa.UniqueConstraint("change_sequence", name=op.f("uq_sync_changes_change_sequence")),
    )
    op.create_index(
        "ix_sync_changes_tenant_sequence",
        "sync_changes",
        ["tenant_id", "change_sequence"],
        unique=False,
    )
    op.create_table(
        "sync_operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("operation_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sync_operations_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("tenant_id", "id", name="pk_sync_operations"),
    )
    op.create_index(
        "ix_sync_operations_tenant_device",
        "sync_operations",
        ["tenant_id", "device_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_sync_operations_tenant_entity",
        "sync_operations",
        ["tenant_id", "entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_sync_operations_tenant_occurred",
        "sync_operations",
        ["tenant_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_sync_operations_tenant_status",
        "sync_operations",
        ["tenant_id", "status", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "sync_cursors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("last_server_sequence", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_sync_cursors_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_sync_cursors_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_cursors")),
        sa.UniqueConstraint("tenant_id", "device_id", name="uq_sync_cursors_tenant_id_device_id"),
    )
    op.create_index(
        "ix_sync_cursors_tenant_sequence",
        "sync_cursors",
        ["tenant_id", "last_server_sequence"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_cursors_tenant_sequence", table_name="sync_cursors")
    op.drop_table("sync_cursors")
    op.drop_index("ix_sync_operations_tenant_status", table_name="sync_operations")
    op.drop_index("ix_sync_operations_tenant_occurred", table_name="sync_operations")
    op.drop_index("ix_sync_operations_tenant_entity", table_name="sync_operations")
    op.drop_index("ix_sync_operations_tenant_device", table_name="sync_operations")
    op.drop_table("sync_operations")
    op.drop_index("ix_sync_changes_tenant_sequence", table_name="sync_changes")
    op.drop_table("sync_changes")
    # ### end Alembic commands ###
