"""Database engine, session lifecycle, declarative base and the unit of work.

This is the only module that constructs a database driver. Everything else
receives database capability through injected abstractions, because the rule
that a service never knows how PostgreSQL works is only real if there is exactly
one place where PostgreSQL is configured.

The unit of work deserves a note. A service must be able to wrap several
repository calls in one transaction without importing SQLAlchemy to do it. The
port therefore exposes an opaque ``session_handle`` which a service passes to
CRUD functions and never inspects. CRUD, which owns persistence, casts it to a
session. The architecture contracts enforce the rest: no module under
``services/`` may import a database driver, and a test asserts it.
"""

from __future__ import annotations

import logging
from collections.abc import AsyncIterator, Callable
from contextlib import asynccontextmanager
from types import TracebackType
from typing import Any, Final, Protocol

from sqlalchemy import MetaData, text
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)
from sqlalchemy.orm import DeclarativeBase

from ahia.core.config import Settings
from ahia.core.errors import PersistenceError
from ahia.core.logging import StructuredLogger, get_logger

_DATABASE_LOGGER_NAME: Final[str] = "ahia.core.database"

#: Constraint and index naming. A deterministic name is what makes an Alembic
#: autogenerated migration reviewable, and what makes a constraint actionable in
#: a PostgreSQL error message.
NAMING_CONVENTION: Final[dict[str, str]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def build_connect_arguments(settings: Settings) -> dict[str, Any]:
    """Return the driver-level connection arguments derived from configuration.

    A separate, pure function rather than an inline dictionary so the
    connection shape can be asserted directly. A settings-derived safety
    property that is only tested through a live connection is a property that
    can regress without any test noticing.
    """
    connect_arguments: dict[str, Any] = {
        "server_settings": {
            # A slow query is bounded by the server, not by hope.
            "statement_timeout": str(settings.database_statement_timeout_ms),
            # Identifies this application in the server's activity view, which
            # is the difference between a five-minute and a one-hour incident
            # when something is holding a lock.
            "application_name": f"{settings.app_name.lower()}-api",
        }
    }
    if settings.database_require_ssl:
        connect_arguments["ssl"] = "require"
    return connect_arguments


class Base(DeclarativeBase):
    """Declarative base for every persistence record.

    Persistence records are ``*Record`` classes that live inside a CRUD module.
    They are not domain entities: the domain model is framework-free, and the
    mapping between the two happens at the persistence boundary (ADR-0001).
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Database:
    """Owns the async engine and the session factory.

    Constructed once in the composition root. It is not a module-level
    singleton, so a test can create one against a test database without
    affecting anything else.
    """

    def __init__(
        self,
        settings: Settings,
        *,
        engine: AsyncEngine | None = None,
        logger: StructuredLogger | None = None,
    ) -> None:
        self._settings = settings
        self._logger = (logger or get_logger(_DATABASE_LOGGER_NAME)).bind(component="database")
        self._engine = engine or self._build_engine(settings)
        self._session_factory: async_sessionmaker[AsyncSession] = async_sessionmaker(
            bind=self._engine,
            expire_on_commit=False,
            autoflush=False,
        )

    @staticmethod
    def _build_engine(settings: Settings) -> AsyncEngine:
        """Create the engine from configuration.

        Pool settings and the statement timeout are applied here, so a slow
        query is bounded by the server rather than by hope, and one process
        cannot exhaust the database's connection slots.
        """
        return create_async_engine(
            settings.database_url,
            pool_size=settings.database_pool_size,
            max_overflow=settings.database_max_overflow,
            pool_timeout=settings.database_pool_timeout_seconds,
            pool_pre_ping=True,
            echo=False,
            connect_args=build_connect_arguments(settings),
        )

    @property
    def engine(self) -> AsyncEngine:
        return self._engine

    @property
    def session_factory(self) -> async_sessionmaker[AsyncSession]:
        return self._session_factory

    @asynccontextmanager
    async def session(self) -> AsyncIterator[AsyncSession]:
        """Yield a session for the duration of a block.

        The session is closed on exit even when the block raises. Transaction
        control belongs to the unit of work, not here.
        """
        session = self._session_factory()
        try:
            yield session
        finally:
            await session.close()

    async def check_connectivity(self) -> bool:
        """Return True when the database answers a trivial query.

        Used by the readiness endpoint. It never raises and never returns the
        failure reason: a readiness probe is public, and the reason a database is
        unreachable is exactly the kind of thing not to publish.
        """
        try:
            async with self._engine.connect() as connection:
                await connection.execute(text("SELECT 1"))
        except Exception as error:  # noqa: BLE001 - readiness must never raise
            self._logger.error(
                "database_connectivity_check_failed",
                error_type=type(error).__name__,
            )
            return False
        return True

    async def dispose(self) -> None:
        """Close every pooled connection. Called from application shutdown."""
        await self._engine.dispose()
        self._logger.info("database_engine_disposed")

    def transaction_scope(self) -> SqlAlchemyUnitOfWork:
        """Return a new unit of work bound to a fresh session.

        A new scope per use case, because a shared one would make two concurrent
        requests share a transaction.
        """
        return SqlAlchemyUnitOfWork(self._session_factory, logger=self._logger)

    def unit_of_work_factory(self) -> Callable[[], SqlAlchemyUnitOfWork]:
        """Return a callable that produces a unit of work.

        This is what the composition root injects into a service, so the service
        can open a transaction without knowing what implements it.
        """
        return self.transaction_scope


class UnitOfWork(Protocol):
    """The transaction port a service depends on.

    A service may commit, roll back, and pass ``session_handle`` to CRUD
    functions. It may not inspect the handle: doing so would make the service
    depend on the database, which is the rule this port exists to preserve.

    The context manager methods are part of the port because entering the scope
    is what opens the session. Exiting without committing rolls back, so an
    unfinished use case leaves no trace.
    """

    async def __aenter__(self) -> UnitOfWork: ...

    async def __aexit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...

    @property
    def session_handle(self) -> Any: ...


class SqlAlchemyUnitOfWork:
    """A transaction boundary backed by one SQLAlchemy async session."""

    def __init__(
        self,
        session_factory: async_sessionmaker[AsyncSession],
        *,
        logger: StructuredLogger | None = None,
    ) -> None:
        self._session_factory = session_factory
        self._session: AsyncSession | None = None
        self._logger = logger or get_logger(_DATABASE_LOGGER_NAME)
        self._completed = False

    @property
    def session_handle(self) -> Any:
        """Return the session for CRUD functions.

        Deliberately typed as ``Any``: the type exists so CRUD can cast it, and
        the contract is that nothing else touches it.
        """
        if self._session is None:
            raise PersistenceError(
                operation="acquire_session",
                detail="unit of work used outside its context manager",
            )
        return self._session

    async def __aenter__(self) -> SqlAlchemyUnitOfWork:
        self._session = self._session_factory()
        self._completed = False
        return self

    async def __aexit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        """Close the session, rolling back an unfinished transaction.

        An exception inside the block rolls back: a partial business operation
        must leave no trace. A block that exits without committing also rolls
        back, because silence is not consent to write.
        """
        session = self._session
        self._session = None
        if session is None:
            return
        try:
            if not self._completed:
                await session.rollback()
        finally:
            await session.close()

    async def commit(self) -> None:
        """Commit the transaction.

        Every write in a use case is committed once, here, after all of its
        parts have succeeded. A half-created sale is not an acceptable outcome.
        """
        if self._session is None:
            raise PersistenceError(
                operation="commit_transaction",
                detail="unit of work used outside its context manager",
            )
        try:
            await self._session.commit()
        except Exception as error:
            await self._session.rollback()
            self._completed = True
            raise PersistenceError(
                operation="commit_transaction",
                detail=f"commit failed and was rolled back: {type(error).__name__}",
                cause=error,
            ) from error
        self._completed = True

    async def rollback(self) -> None:
        """Roll the transaction back explicitly."""
        if self._session is None:
            raise PersistenceError(
                operation="rollback_transaction",
                detail="unit of work used outside its context manager",
            )
        await self._session.rollback()
        self._completed = True


def configure_sqlalchemy_logging(settings: Settings) -> None:
    """Quiet SQLAlchemy's own logger unless the application is in debug.

    Its default configuration writes parameter values at INFO, which is exactly
    the kind of accidental disclosure the structured logger exists to prevent.
    """
    sqlalchemy_logger = logging.getLogger("sqlalchemy.engine")
    sqlalchemy_logger.setLevel(logging.INFO if settings.log_level == "DEBUG" else logging.WARNING)
