"""Tests for the database lifecycle and the unit of work.

The connection-shape tests are unit tests: they assert the engine was built from
configuration. The transactional tests are integration tests against the real
test database, because a rollback guarantee that is only asserted against a mock
is not a guarantee.
"""

from __future__ import annotations

import logging
import os
from typing import Any

import pytest
from sqlalchemy import Column, Integer, MetaData, Table, func, select, text
from sqlalchemy.ext.asyncio import create_async_engine

from ahia.core.config import AppEnvironment, Settings, StorageProviderName
from ahia.core.database import (
    NAMING_CONVENTION,
    Base,
    Database,
    build_connect_arguments,
    configure_sqlalchemy_logging,
)
from ahia.core.errors import PersistenceError

DEFAULT_TEST_DATABASE_URL = (
    "postgresql+asyncpg://ksschkw:ahia_local_dev_only@127.0.0.1:5432/ahia_test"
)


def build_settings(**overrides: Any) -> Settings:
    baseline: dict[str, Any] = {
        "_env_file": None,
        "app_env": AppEnvironment.TEST,
        "database_url": os.environ.get("TEST_DATABASE_URL", DEFAULT_TEST_DATABASE_URL),
        "jwt_secret": "test-signing-secret-value-0000000001",
        "refresh_token_pepper": "test-refresh-pepper-value-00000000011",
        "storage_provider": StorageProviderName.R2,
        "r2_endpoint": "https://account.r2.cloudflarestorage.com",
        "r2_access_key_id": "r2-access-key",
        "r2_secret_access_key": "r2-secret-key",
        "r2_bucket": "ahia-test",
    }
    baseline.update(overrides)
    return Settings(**baseline)


@pytest.fixture(scope="session")
def test_database_url() -> str:
    return os.environ.get("TEST_DATABASE_URL", DEFAULT_TEST_DATABASE_URL)


@pytest.fixture
async def database(test_database_url: str) -> Any:
    settings = build_settings(database_url=test_database_url)
    instance = Database(settings)
    try:
        yield instance
    finally:
        await instance.dispose()


# ---------------------------------------------------------------------------
# Engine configuration
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_engine_is_built_from_configuration() -> None:
    settings = build_settings(
        database_pool_size=7,
        database_max_overflow=3,
        database_pool_timeout_seconds=4.0,
    )

    database = Database(settings)

    assert str(database.engine.url).startswith("postgresql+asyncpg://")
    assert database.engine.pool.size() == 7  # type: ignore[attr-defined]
    assert database.engine.pool._max_overflow == 3  # type: ignore[attr-defined]


@pytest.mark.unit
def test_statement_timeout_is_applied_server_side() -> None:
    connect_arguments = build_connect_arguments(
        build_settings(database_statement_timeout_ms=12_345)
    )

    assert connect_arguments["server_settings"]["statement_timeout"] == "12345"
    assert connect_arguments["server_settings"]["application_name"] == "ahia-api"


@pytest.mark.unit
def test_tls_is_requested_when_configuration_requires_it() -> None:
    assert build_connect_arguments(build_settings(database_require_ssl=True))["ssl"] == "require"


@pytest.mark.unit
def test_tls_is_not_forced_locally() -> None:
    assert "ssl" not in build_connect_arguments(build_settings(database_require_ssl=False))


@pytest.mark.unit
def test_naming_convention_covers_every_constraint_kind() -> None:
    """Deterministic names are what make an autogenerated migration reviewable."""
    assert set(NAMING_CONVENTION) == {"ix", "uq", "ck", "fk", "pk"}
    assert Base.metadata.naming_convention is not None


@pytest.mark.unit
def test_sqlalchemy_logging_is_quiet_outside_debug() -> None:
    configure_sqlalchemy_logging(build_settings(log_level="INFO"))
    assert logging.getLogger("sqlalchemy.engine").level == logging.WARNING

    configure_sqlalchemy_logging(build_settings(log_level="DEBUG"))
    assert logging.getLogger("sqlalchemy.engine").level == logging.INFO


# ---------------------------------------------------------------------------
# Unit of work semantics
# ---------------------------------------------------------------------------


@pytest.mark.unit
async def test_unit_of_work_refuses_use_outside_its_context_manager(
    test_database_url: str,
) -> None:
    unit_of_work = Database(build_settings(database_url=test_database_url)).transaction_scope()

    with pytest.raises(PersistenceError, match="outside its context manager"):
        _ = unit_of_work.session_handle

    with pytest.raises(PersistenceError, match="outside its context manager"):
        await unit_of_work.commit()


PROBE_TABLE_NAME = "ahia_transaction_probe"
PROBE_TABLE = Table(PROBE_TABLE_NAME, MetaData(), Column("value", Integer))


@pytest.fixture
async def probe_table(database: Database) -> Any:
    """Create the probe table and drop it afterwards.

    The table is a real one, not a temporary one: a temporary table lives and
    dies with its session, so it cannot demonstrate that a rollback in one
    session is invisible to the next.

    Rows, inserts and counts all go through SQLAlchemy Core constructs rather
    than interpolated SQL strings, so the test exercises the same parameterised
    path production code uses.
    """
    async with database.transaction_scope() as setup_unit_of_work:
        await setup_unit_of_work.session_handle.execute(
            text(f"DROP TABLE IF EXISTS {PROBE_TABLE_NAME}")
        )
        await setup_unit_of_work.session_handle.execute(
            text(f"CREATE TABLE {PROBE_TABLE_NAME} (value INTEGER)")
        )
        await setup_unit_of_work.commit()
    try:
        yield PROBE_TABLE
    finally:
        async with database.transaction_scope() as cleanup_unit_of_work:
            await cleanup_unit_of_work.session_handle.execute(
                text(f"DROP TABLE IF EXISTS {PROBE_TABLE_NAME}")
            )
            await cleanup_unit_of_work.commit()


async def count_probe_rows(database: Database) -> int:
    """Return the number of rows currently visible in the probe table."""
    async with database.transaction_scope() as unit_of_work:
        result = await unit_of_work.session_handle.execute(
            select(func.count()).select_from(PROBE_TABLE)
        )
        return int(result.scalar_one())


@pytest.mark.integration
async def test_commit_persists_rows(database: Database, probe_table: Table) -> None:
    async with database.transaction_scope() as unit_of_work:
        await unit_of_work.session_handle.execute(
            probe_table.insert().values([{"value": 1}, {"value": 2}])
        )
        await unit_of_work.commit()

    assert await count_probe_rows(database) == 2


@pytest.mark.integration
async def test_rollback_discards_rows(database: Database, probe_table: Table) -> None:
    async with database.transaction_scope() as unit_of_work:
        await unit_of_work.session_handle.execute(probe_table.insert().values(value=1))
        await unit_of_work.rollback()

    assert await count_probe_rows(database) == 0


@pytest.mark.integration
async def test_exception_inside_the_block_rolls_back(
    database: Database, probe_table: Table
) -> None:
    class DeliberateFailureError(Exception):
        """Raised to prove the transaction does not survive an exception."""

    with pytest.raises(DeliberateFailureError):
        async with database.transaction_scope() as unit_of_work:
            await unit_of_work.session_handle.execute(probe_table.insert().values(value=1))
            raise DeliberateFailureError

    assert await count_probe_rows(database) == 0


@pytest.mark.integration
async def test_block_that_neither_commits_nor_raises_rolls_back(
    database: Database, probe_table: Table
) -> None:
    """Silence is not consent to write."""
    async with database.transaction_scope() as unit_of_work:
        await unit_of_work.session_handle.execute(probe_table.insert().values(value=1))
        # No commit.

    assert await count_probe_rows(database) == 0


@pytest.mark.integration
async def test_session_is_closed_on_exit(database: Database) -> None:
    unit_of_work = database.transaction_scope()
    async with unit_of_work:
        await unit_of_work.session_handle.execute(text("SELECT 1"))

    with pytest.raises(PersistenceError):
        _ = unit_of_work.session_handle


# ---------------------------------------------------------------------------
# Readiness
# ---------------------------------------------------------------------------


@pytest.mark.integration
async def test_connectivity_check_succeeds_against_the_test_database(database: Database) -> None:
    assert await database.check_connectivity() is True


@pytest.mark.integration
async def test_connectivity_check_returns_false_rather_than_raising() -> None:
    """A readiness probe answers; it does not throw a stack trace at the caller."""
    unreachable = create_async_engine(
        "postgresql+asyncpg://nobody:nobody@127.0.0.1:59999/absent",
        pool_pre_ping=True,
    )
    instance = Database(build_settings(), engine=unreachable)

    assert await instance.check_connectivity() is False

    await instance.dispose()
